# Generated by Django 5.2.7 on 2025-11-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='discipline',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
