# Generated by Django 5.2.7 on 2025-12-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_classgroup_name_alter_task_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='total_completed',
        ),
    ]
