# Generated by Django 5.2.7 on 2025-12-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_userstats_total_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='is_personal',
        ),
    ]
