# Generated by Django 5.2.7 on 2025-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_classgroup_is_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
