# Generated by Django 5.2.6 on 2025-09-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_classgroup_members_alter_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='discipline',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
